In [ ]:
# @toffanetto
import numpy as np
import classification as cl

In [ ]:
# Getting train data
X_train, y_train = cl.getData(train=True, raw= False)

# Getting test data
X_test, y_test = cl.getData(train=False, raw= False)

In [80]:
NUMBER_OF_CLASSES = 6
NUMBER_OF_ATRIBUTES = 561

STEP = 0.005

def trainClassifier(X, y):
    W = np.random.rand(NUMBER_OF_CLASSES, NUMBER_OF_ATRIBUTES)/100 # Rand values in the interval (0, 0,01)

    y_ohe = cl.oneHotEncoding(y=y)

    print('x_train.shape = '+str(X.shape))
    print('W.shape = '+str(W.shape))

    for i in range(1):

        Xi = X[i, np.newaxis] 
        
        y_hat = Xi.dot(W.T)
        
        dJCE = (y_ohe[i] - y_hat).T.dot(Xi)
        
        W = W - STEP*dJCE
        
        print(np.mean(y_ohe[i] - y_hat))
        
    print(W)
    
    return W
    
W = trainClassifier(X=X_train,y=y_train)

# Training

x_train.shape = (7352, 561)
W.shape = (6, 561)
1.8954789143001964
[[0.00679244 0.0084081  0.00150873 ... 0.0031358  0.00980577 0.00430488]
 [0.00729445 0.00891055 0.00277325 ... 0.00900694 0.0089297  0.00400647]
 [0.00563618 0.00063189 0.00857956 ... 0.00212864 0.00078188 0.00841971]
 [0.00662805 0.00711535 0.00685627 ... 0.00863918 0.00020697 0.00218605]
 [0.00855543 0.0041532  0.00926085 ... 0.00572031 0.00235689 0.00055114]
 [0.00064312 0.00643205 0.00941392 ... 0.00802712 0.00052513 0.00601173]]


In [35]:
X_train[0].shape

(561,)

In [39]:
y_hat.T.shape

(6,)