In [1]:
# @toffanetto
import numpy as np
import classification as cl
import matplotlib.pyplot as plt

/home/toffanetto/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "


In [2]:
# Getting train data
X_train, y_train = cl.getData(train=True, raw= False)

# Getting test data
X_test, y_test = cl.getData(train=False, raw= False)

In [3]:
# Training

W, RMSE_sample, hit, not_hit = cl.trainClassifier(X=X_train,y=y_train,batch=False)

In [4]:
# Testing

y_test_hat, class_y_hat = cl.classify(x=X_test,W=W)

# for i in range(len(y_test)):
#     print('| '+str(y_test[i])+' -> '+str(class_y_hat[i]))

confusion_matrix, hit_rate, not_hit_rate = cl.rateModel(y=y_test,y_hat=class_y_hat)

print('Confusion Matrix: \n'+str(confusion_matrix))


Confusion Matrix: 
[[492.   0.   4.   0.   0.   0.]
 [  8. 461.   2.   0.   0.   0.]
 [ 33.  52. 335.   0.   0.   0.]
 [  0.   3.   0. 487.   0.   1.]
 [  1.   2.   0. 268. 261.   0.]
 [  0.   0.   0.   0.   0. 537.]]
